# Generated by Django 5.2.6 on 2025-09-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_grade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='analysis.grade')),
            ],
            options={
                'unique_together': {('name', 'grade')},
            },
        ),
    ]
