# Generated by Django 5.2.6 on 2025-09-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_section_options_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answer_keys/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.subject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('grade', 'section', 'subject')},
            },
        ),
    ]
