# Generated by Django 5.2.6 on 2025-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_answerkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='grade',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
