# Generated by Django 5.2.6 on 2025-10-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_answerkey_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together=set(),
        ),
    ]
