# Generated by Django 5.2.6 on 2025-11-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_answerkey_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='test_sheet',
            field=models.FileField(blank=True, null=True, upload_to='test_sheets/'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together={('user', 'grade', 'section', 'subject')},
        ),
    ]
