# Generated by Django 5.2.6 on 2025-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_answerkey_test_sheet_alter_answerkey_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='item_points',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='total_points',
            field=models.FloatField(default=50),
        ),
    ]
