# Generated by Django 5.2.8 on 2025-12-05 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_answerkey_item_points_answerkey_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('sheet_image', models.ImageField(upload_to='scanned_sheets/')),
                ('answers', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='analysis.answerkey')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.grade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
