# Generated by Django 5.2.8 on 2025-12-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_scanresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='sheet_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
    ]
