# Generated by Django 5.2.8 on 2025-12-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_scanresult_sheet_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='sheet_image',
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
