# Generated by Django 5.2.8 on 2025-12-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_scanresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scanresult',
            name='sheet_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
