# Generated by Django 5.2.8 on 2025-12-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_alter_scanresult_options_scanresult_sheet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Unknown Student', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analysis.section'),
        ),
    ]
