# Generated by Django 5.2.8 on 2025-12-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_remove_student_user_student_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'full_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Used for alphabetical sorting (last name only, e.g. Rosales).', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(blank=True, default='', help_text='Optional middle initial (e.g. D. or M.)', max_length=10),
        ),
    ]
