# Generated by Django 5.2.8 on 2025-12-06 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_alter_student_options_student_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together=set(),
        ),
        # migrations.AlterUniqueTogether(
        #     name='subject',
        #     unique_together={('grade', 'name')},
        # ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Convenience link; usually same as section.grade.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analysis.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='analysis.grade'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='analysis.section'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='analysis.subject'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='test_sheet',
            field=models.FileField(blank=True, null=True, upload_to='answer_key_sheets/'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='analysis.grade'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='analysis.section'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='sheet_image',
            field=models.ImageField(blank=True, null=True, upload_to='scan_sheets/'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='student_name',
            field=models.CharField(blank=True, help_text='Free text; usually matches a Student.formatted_name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='analysis.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(help_text='Given names only (first name + middle name, no surname).', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Last name only (used for alphabetical order).', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(blank=True, default='', help_text='Optional middle initial (e.g. A or A.).', max_length=10),
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='total_points',
        ),
    ]
