# Generated by Django 5.2.8 on 2025-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_alter_answerkey_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
