# Generated by Django 5.2.8 on 2025-12-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_answerkey_total_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('grade', 'name')},
        ),
    ]
