# Generated by Django 5.2.8 on 2025-12-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('school_year', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
