# Generated by Django 5.2.8 on 2025-12-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_customuser_institutionadmin_institutiondetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['number', 'name']},
        ),
        migrations.AddField(
            model_name='grade',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='analysis.institution'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_grade_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('institution', 'number'), name='uniq_grade_number_per_institution'),
        ),
    ]
