# Generated by Django 5.2.8 on 2025-12-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_alter_grade_options_grade_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analysis.institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the institution school year at time of saving (e.g., 2025-2026).', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('institution', 'section', 'full_name', 'last_name', 'middle_initial'), name='uniq_student_name_per_institution_section'),
        ),
    ]
