# Generated by Django 5.2.8 on 2025-12-14 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_teacher_grade_teacher_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='analysis.institution'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='school_year',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddConstraint(
            model_name='answerkey',
            constraint=models.UniqueConstraint(fields=('user', 'institution', 'school_year', 'grade', 'section', 'subject'), name='uniq_answerkey_per_user_inst_year_class'),
        ),
    ]
