# Generated by Django 5.2.8 on 2025-12-14 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_answerkey_institution_answerkey_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='analysis.institution'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='school_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['institution', 'school_year', 'created_at'], name='analysis_sc_institu_9b6800_idx'),
        ),
    ]
