# Generated by Django 5.2.9 on 2025-12-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.grade')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.institution')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='analysis.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'grade', 'section', 'subject', 'institution', 'school_year'), name='uniq_teacher_grade_section_subject_per_sy')],
            },
        ),
    ]
