# Generated by Django 5.2.9 on 2025-12-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_teacherclassassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('correct_choice', models.CharField(max_length=1)),
                ('difficulty_tag', models.CharField(choices=[('Difficult', 'Difficult'), ('Moderate', 'Moderate'), ('Easy', 'Easy')], default='Moderate', max_length=20)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analysis.answerkey')),
            ],
        ),
    ]
