# Generated by Django 5.2.9 on 2025-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='uniq_grade_name_per_institution',
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='uniq_grade_number_per_institution',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='grading_period',
            field=models.CharField(choices=[('1st Grading', '1st Grading'), ('2nd Grading', '2nd Grading')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
