# Generated by Django 5.2.9 on 2025-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_alter_grade_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['number', 'name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grading_period',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('grade', 'name')},
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_grade_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('institution', 'number'), name='uniq_grade_number_per_institution'),
        ),
    ]
