# Generated by Django 5.2.9 on 2025-12-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_alter_grade_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
