# Generated by Django 5.2.9 on 2025-12-15 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_delete_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_periods', to='analysis.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='analysis.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='analysis.institution')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='analysis.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='analysis.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to=settings.AUTH_USER_MODEL)),
                ('grading_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.gradingperiod')),
            ],
        ),
    ]
