# Generated by Django 5.2.9 on 2025-12-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0038_gradingperiod_classassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingperiod',
            name='name',
            field=models.CharField(choices=[('1st Grading', '1st Grading'), ('2nd Grading', '2nd Grading'), ('3rd Grading', '3rd Grading'), ('4th Grading', '4th Grading')], max_length=50),
        ),
    ]
