# Generated by Django 5.2.8 on 2025-12-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_alter_gradingperiod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
