# Generated by Django 5.2.8 on 2025-12-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_institutionadmin_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.institution')),
            ],
        ),
    ]
