# Generated by Django 5.2.8 on 2025-12-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0041_schoolyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingperiod',
            name='name',
        ),
        migrations.AddField(
            model_name='gradingperiod',
            name='period',
            field=models.CharField(choices=[('1st', 'First Grading'), ('2nd', 'Second Grading'), ('3rd', 'Third Grading'), ('4th', 'Fourth Grading')], max_length=4, null=True),
        ),
    ]
