# Generated by Django 5.2.8 on 2025-12-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0042_remove_gradingperiod_name_gradingperiod_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingperiod',
            name='period',
            field=models.CharField(choices=[('1st Grading', 'First'), ('2nd Grading', 'Second'), ('3rd Grading', 'Third'), ('4th Grading', 'Fourth')], max_length=20, null=True),
        ),
    ]
