# Generated by Django 5.2.8 on 2025-12-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0044_alter_gradingperiod_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grading_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='analysis.gradingperiod'),
        ),
    ]
