# Generated by Django 5.2.9 on 2025-12-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0045_grade_grading_period'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherclassassignment',
            name='uniq_teacher_grade_section_subject_per_sy',
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='grading_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.gradingperiod'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'grade', 'section', 'subject', 'grading_period', 'institution', 'school_year'), name='uniq_teacher_class_assignment_per_grading'),
        ),
    ]
