# Generated by Django 5.2.9 on 2025-12-17 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0046_remove_teacherclassassignment_uniq_teacher_grade_section_subject_per_sy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answerkey',
            name='uniq_answerkey_per_user_inst_year_class',
        ),
        migrations.RemoveConstraint(
            model_name='teacherclassassignment',
            name='uniq_teacher_class_assignment_per_grading',
        ),
        migrations.RemoveIndex(
            model_name='scanresult',
            name='analysis_sc_institu_9b6800_idx',
        ),
        migrations.RemoveField(
            model_name='teacherclassassignment',
            name='grading_period',
        ),
        migrations.AddField(
            model_name='answerkey',
            name='grading_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_keys', to='analysis.gradingperiod'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='grading_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_results', to='analysis.gradingperiod'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['institution', 'school_year', 'grading_period', 'created_at'], name='analysis_sc_institu_c74fb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerkey',
            constraint=models.UniqueConstraint(fields=('user', 'institution', 'school_year', 'grading_period', 'grade', 'section', 'subject'), name='uniq_answerkey_per_user_inst_year_gp_class'),
        ),
        migrations.AddConstraint(
            model_name='scanresult',
            constraint=models.UniqueConstraint(fields=('answer_key', 'grading_period', 'student_name'), name='uniq_scan_per_student_per_gp'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'grade', 'section', 'subject', 'institution', 'school_year'), name='uniq_teacher_grade_section_subject_per_sy'),
        ),
    ]
