# Generated by Django 5.2.10 on 2026-01-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_remove_answerkey_uniq_answerkey_per_user_inst_year_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingperiod',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
