# Generated by Django 5.2.8 on 2026-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0048_gradingperiod_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
