# Generated by Django 5.2.8 on 2026-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0049_scanresult_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
