# Generated by Django 5.2.8 on 2026-02-07 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0050_answerkey_total_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answerkey',
            name='uniq_answerkey_per_user_inst_year_gp_class',
        ),
        migrations.AddField(
            model_name='answerkey',
            name='quiz_name',
            field=models.CharField(default='Default Quiz', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='answerkey',
            constraint=models.UniqueConstraint(fields=('user', 'institution', 'school_year', 'grading_period', 'grade', 'section', 'subject', 'quiz_name'), name='uniq_answerkey_per_user_inst_year_gp_class_quiz'),
        ),
    ]
