# Generated by Django 5.2.8 on 2026-02-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0051_remove_answerkey_uniq_answerkey_per_user_inst_year_gp_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='analysis.student'),
        ),
    ]
