# Generated by Django 5.2.8 on 2026-02-12 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0052_scanresult_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkey',
            name='school_year',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9),
        ),
        migrations.AlterConstraint(
            model_name='answerkey',
            name='uniq_answerkey_per_user_inst_year_gp_class_quiz',
            constraint=models.UniqueConstraint(fields=('user', 'institution', 'school_year', 'grading_period', 'grade', 'section', 'subject', 'quiz_name'), name='uniq_answerkey_per_user_inst_year_gp_class_quiz', violation_error_message='An answer key with this quiz name already exists for this period.'),
        ),
    ]
