# Generated by Django 5.2.8 on 2026-02-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0053_alter_answerkey_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='analysis.schoolyear'),
        ),
    ]
