# Generated by Django 5.2.8 on 2026-02-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0054_grade_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(fields=('institution', 'year'), name='uniq_sy_per_institution'),
        ),
    ]
