# Generated by Django 5.2.8 on 2026-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0056_assessmentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
