# Generated by Django 6.0.3 on 2026-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0058_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingperiod',
            name='period',
            field=models.CharField(choices=[('1st Grading', '1st Grading'), ('2nd Grading', '2nd Grading'), ('3rd Grading', '3rd Grading'), ('4th Grading', '4th Grading'), ('Prelim', 'Prelim'), ('Midterm', 'Midterm'), ('Semi-Finals', 'Semi-Finals'), ('Finals', 'Finals'), ('Exam', 'Exam')], max_length=20, null=True),
        ),
    ]
